name: DXF Export

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install freecad
        run: |
          sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
          sudo apt-get update
          sudo apt-get install freecad -y
    
      - name: Run FreeCAD
        run: |
            mkdir /tmp/mirte-frame
            cp -r ./freecadFiles/* /tmp/mirte-frame
            cp -r ./scripts/generate.py /tmp/mirte-frame
            echo "exec(open(\"/tmp/mirte-frame/generate.py\").read())" | freecadcmd
      - name: Upload DXF
        uses: actions/upload-artifact@v4
        with:
          name: dxfs
          path: /tmp/mirte-frame/*.dxf
      - name: Upload STL
        uses: actions/upload-artifact@v4
        with:
          name: stls
          path: /tmp/mirte-frame/*.stl
      - name: zip files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd /tmp/mirte-frame
          zip -r /tmp/mirte-frame-stl.zip ./*.stl
          zip -r /tmp/mirte-frame-dxf.zip ./*.dxf
      - name: Push to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: 
              /tmp/mirte-frame-dxf.zip
              /tmp/mirte-frame-stl.zip

