name: render steps

on:
  [push]

jobs:
  screenshots:
    strategy:
      matrix:
        mirte: [pioneer, basic]
        type: [pcb, breadboard]
    container: ghcr.io/arendjan/mirte-frame:renderworkflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: install freecad
      #   run: |
      #     sudo ./install.sh
    
      - name: Run FreeCAD
        run: |
            apt update
            apt install python3-pyqt5 python3-pip git wget -y
            pip3 install git+https://github.com/arendjan/freecad-build-instruction-generator.git@fix-mkdir
            cd scripts/build_instructions/
            rm -rf warnings
            git clone https://github.com/mklomp/mirte-release.git warnings
            cd ../../
            wget https://mirte.arend-jan.com/files/test/steps.zip #TODO: change to latest version
            mkdir build/step -p
            unzip steps.zip -d build/step
            mkdir /tmp/mirte-frame
            cp -r ./ /tmp/mirte-frame
            cd /tmp/mirte-frame
            ls
            ./testFree.sh ${{ matrix.mirte }} ${{ matrix.type }}


      - name: Upload img
        uses: actions/upload-artifact@v4
        with:
          name: build_instructions_${{ matrix.mirte }}_${{ matrix.type }}
          path: /tmp/mirte-frame/scripts/build_instructions/mirte_pioneer/build
      
      - name: Push to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
              /tmp/mirte-frame/scripts/build_instructions/mirte_pioneer/build

